name: bootcamperciyes_final_project
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.5.0
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.0
  share_plus: ^7.2.1
  flutter_bloc: ^8.1.3
  animated_text_kit: ^4.2.2
  google_sign_in: ^6.1.6
  easy_localization: ^3.0.3
  geolocator: ^10.1.0
  ionicons: ^0.2.2
  googleapis: ^12.0.0
  googleapis_auth: ^1.4.1
  equatable: ^2.0.5
  loading_animation_widget: ^1.2.0+4
  country_flags: ^2.2.0
  recase: ^4.1.0
  hive: ^2.2.3
  path_provider: ^2.1.1
  firebase_core: ^2.24.0
  firebase_auth: ^4.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/languages/
