// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkRH9Fb41oyEk80Ji8npSDt51mfBd-UEU',
    appId: '1:722713212461:android:09a4fe8b52a937c0a32aa4',
    messagingSenderId: '722713212461',
    projectId: 'bootcamperciyes-final',
    storageBucket: 'bootcamperciyes-final.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT1qUU9GLuplP9f3nI3-GQ1BSYrfQOPJs',
    appId: '1:722713212461:ios:b506fbdabf27d3f3a32aa4',
    messagingSenderId: '722713212461',
    projectId: 'bootcamperciyes-final',
    storageBucket: 'bootcamperciyes-final.appspot.com',
    androidClientId: '722713212461-3pijcd85ph37tlg9crdjku78o97kd3sc.apps.googleusercontent.com',
    iosClientId: '722713212461-id8lbdd2bn562ojdrhkqhjmm2gl9319h.apps.googleusercontent.com',
    iosBundleId: 'com.moonshred.bootcamperciyesFinalProject',
  );
}
